import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getActiveAllocation, getRegenerationStatus } from "@/lib/allocation";
import { listParticipants, listCandidateStudents } from "@/lib/session-roster";
import { formatDate, formatTime, formatYear } from "@/lib/format";
import { GenerateControls } from "./GenerateControls";
import { AllocationList } from "./AllocationList";
import { ExportPanel } from "./ExportPanel";
import { ManageStudents } from "./ManageStudents";

export default async function SessionDetailPage(
  props: PageProps<"/sessions/[id]">,
) {
  const user = await requireUser();
  const { id } = await props.params;

  const session = await prisma.examSession.findUnique({ where: { id } });
  if (!session) notFound();

  const [participants, allocation, regenStatus, candidates] = await Promise.all([
    listParticipants(id),
    getActiveAllocation(id),
    getRegenerationStatus(id),
    user.role === "ADMIN" ? listCandidateStudents(id) : Promise.resolve([]),
  ]);

  const studentCount = participants.length;

  const countsByProgram = new Map<string, number>();
  for (const s of participants) {
    countsByProgram.set(s.program.name, (countsByProgram.get(s.program.name) ?? 0) + 1);
  }
  const programCounts = [...countsByProgram.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  const rosterRows = participants.map((s) => ({
    id: s.id,
    matricNumber: s.matricNumber,
    fullName: s.fullName,
    program: s.program.name,
    year: formatYear(s.year),
  }));
  const candidateRows = candidates.map((s) => ({
    id: s.id,
    matricNumber: s.matricNumber,
    fullName: s.fullName,
    program: s.program.name,
    year: formatYear(s.year),
  }));

  const rows =
    allocation?.seatAssignments.map((a) => ({
      studentId: a.studentId,
      seatNumber: a.seatNumber,
      matricNumber: a.student.matricNumber,
      fullName: a.student.fullName,
      program: a.student.program.name,
    })) ?? [];

  return (
    <main className="flex flex-1 flex-col gap-5 px-4 py-6 sm:px-6">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-semibold text-slate-900">
          {formatYear(session.year)}
          {session.label ? ` — ${session.label}` : ""}
        </h1>
        <Link href="/sessions" className="text-sm text-slate-500">
          Back
        </Link>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white px-4 py-4 text-sm text-slate-600 shadow-sm">
        <p>
          {formatDate(session.date)} · {formatTime(session.startTime)}–
          {formatTime(session.endTime)}
        </p>
        {allocation && (
          <p className="mt-1">
            Active allocation: version {allocation.version} · generated by{" "}
            {allocation.generatedBy.name} on{" "}
            {formatDate(allocation.generatedAt)}
          </p>
        )}
      </div>

      <div className="grid grid-cols-3 gap-3">
        <SessionStat label="Programs" value={programCounts.length} />
        <SessionStat label="Students" value={studentCount} />
        <SessionStat label="Allocated" value={allocation ? "Yes" : "No"} />
      </div>

      {programCounts.length > 0 && (
        <div className="rounded-xl border border-slate-200 bg-white px-4 py-4 shadow-sm">
          <p className="mb-2 text-sm font-semibold text-slate-900">
            Programs in this session
          </p>
          <ul className="flex flex-col gap-1.5">
            {programCounts.map((p) => (
              <li
                key={p.name}
                className="flex items-center justify-between text-sm text-slate-600"
              >
                <span>{p.name}</span>
                <span className="font-medium text-slate-900">{p.count}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {user.role === "ADMIN" && (
        <ManageStudents
          examSessionId={id}
          participants={rosterRows}
          candidates={candidateRows}
        />
      )}

      <GenerateControls
        examSessionId={id}
        hasAllocation={regenStatus.hasAllocation}
        currentVersion={regenStatus.currentVersion}
        invigilatorRegenerationAvailable={
          regenStatus.invigilatorRegenerationAvailable
        }
        userRole={user.role}
      />

      {allocation && <ExportPanel examSessionId={id} />}

      {user.role === "ADMIN" && allocation && (
        <Link
          href={`/sessions/${id}/audit`}
          className="text-center text-sm text-slate-500 underline"
        >
          View Audit History
        </Link>
      )}

      {allocation && <AllocationList examSessionId={id} rows={rows} />}
    </main>
  );
}

function SessionStat({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-center shadow-sm">
      <p className="text-lg font-bold text-slate-900">{value}</p>
      <p className="text-xs text-slate-500">{label}</p>
    </div>
  );
}
