import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getActiveAllocation, getRegenerationStatus } from "@/lib/allocation";
import { formatDate, formatTime, formatYear } from "@/lib/format";
import { GenerateControls } from "./GenerateControls";
import { AllocationList } from "./AllocationList";

export default async function SessionDetailPage(
  props: PageProps<"/sessions/[id]">,
) {
  const user = await requireUser();
  const { id } = await props.params;

  const session = await prisma.examSession.findUnique({ where: { id } });
  if (!session) notFound();

  const [studentCount, allocation, regenStatus] = await Promise.all([
    prisma.student.count({ where: { year: session.year } }),
    getActiveAllocation(id),
    getRegenerationStatus(id),
  ]);

  const rows =
    allocation?.seatAssignments.map((a) => ({
      seatNumber: a.seatNumber,
      matricNumber: a.student.matricNumber,
      fullName: a.student.fullName,
      program: a.student.program.name,
    })) ?? [];

  return (
    <main className="flex flex-1 flex-col gap-5 px-4 py-6 sm:px-6">
      <div className="flex items-center justify-between">
        <h1 className="text-lg font-semibold text-slate-900">
          {formatYear(session.year)}
          {session.label ? ` — ${session.label}` : ""}
        </h1>
        <Link href="/sessions" className="text-sm text-slate-500">
          Back
        </Link>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white px-4 py-4 text-sm text-slate-600 shadow-sm">
        <p>
          {formatDate(session.date)} · {formatTime(session.startTime)}–
          {formatTime(session.endTime)}
        </p>
        <p className="mt-1">
          {studentCount} registered student{studentCount === 1 ? "" : "s"}
        </p>
        {allocation && (
          <p className="mt-1">
            Active allocation: version {allocation.version} · generated by{" "}
            {allocation.generatedBy.name} on{" "}
            {formatDate(allocation.generatedAt)}
          </p>
        )}
      </div>

      <GenerateControls
        examSessionId={id}
        hasAllocation={regenStatus.hasAllocation}
        currentVersion={regenStatus.currentVersion}
        invigilatorRegenerationAvailable={
          regenStatus.invigilatorRegenerationAvailable
        }
        userRole={user.role}
      />

      {allocation && <AllocationList rows={rows} />}
    </main>
  );
}
